### PR TITLE
Support codecov

### PR DESCRIPTION
**Pull request by abatilo**
_**Add XML reporting in a non-junit format**_

It turns out that codecov can't pickup the xunit format xml coverage
files. But adding the generic one that comes with pytest seems to work!

### CODE REVIEW

**Comment by vltr** [comment]
Hello, @abatilo !

Wow, I can't even express how happy I am for all these changes (and the "_OMG how could I've missed that_" on a57c393). Really great work.

Also, I've seen in your commit comments that you were thinking in forking this project. Well, you might not have to. Just after making `sanic-attrs`, I realized that I could decouple the model schema and created [`middle`](https://github.com/vltr/middle), that have a lot of newer features and is blazing fast in pure Python (faster than a lot of other SerDe frameworks and faster than `cattrs` the last time I benchmarked it). It still needs a lot of work but it already has a "sister project", [`middle-schema`](https://github.com/vltr/middle-schema), ~which does have the same bug you found in `sanic-attrs` and I need to fix that~ :laughing:

Anyway, all of this is to make a lean approach on a better version of `sanic-attrs` (that I haven't decided the name yet) and, at the same time, DRY. I'm also developing a plugin for Sanic to enable developers to inject components and dependencies on handlers, very much inspired by Apistar. So, you will be able to create, let's say, a `JSONModel` generic type and write your handlers, something like this:

```python
async def some_handler(input: JSONModel[MyModel]) -> JSONModel[ResponseModel]:
    pass
```

And have a component that transforms the `request.body` to `MyModel` and send it to the handler directly as an instance. With this, later, it'll be even possible to map inputs and outputs to generate schemas and specs with very low boilerplate code to create a handler.

I'm leaning towards giving you a choice: if you like `sanic-attrs` the way it is and would like to move it forward, I can handle this project so you can continue it, because (shame on me) I forgot to archive it. Also, I will give you the pypi register of `sanic-attrs`, of course :wink:

But, if you want to see the "newer" version of this instead, I must say that you would have to wait some time yet, mostly because I need to see some issues regarding the Sanic framework itself (it's never supposed to be easy, eh?).

Cheers,
Richard.

**Comment by vltr** [comment]
Well, I see you already made a fork and published to pypi. You mind if I close this PR, archive the project and redirect to your fork?

**Comment by abatilo** [comment]
Hey @vltr 

It would be great if you could redirect to my fork!

I'm still getting it up and running. The timing was kind of poor on my end. Had I not published yesterday, I would have loved to just take over and be the maintainer for sanic-attrs.

I have a fairly immediate need for doing what sanic-attrs does, so I'm inclined to use it as is and work on it.

Maybe in the future, we could collaborate on your new project.

Excited to hear your thoughts!

Thanks,
Aaron

**Comment by vltr** [comment]
Great, thanks a lot @abatilo !

I'll be glad to redirect to your fork :smiley:

All my best,
Richard.

**Pull request closed without merging**
